export enum JobStatus {
  NEW = 'new',
  LATER = 'later',
  APPLIED = 'applied',
  RECRUITER_SCREEN = 'recruiter_screen',
  TECHNICAL_SCREEN = 'technical_screen',
  HM_SCREEN = 'hm_screen',
  ON_SITE = 'on_site',
  OFFER = 'offer',
  REJECTED = 'rejected',
  NO_NEWS = 'no_news',
  UNFIT = 'unfit',
  EXPIRED = 'expired',
  LOW_SALARY = 'low_salary',
  RETIRED = 'retired',
  DUPLICATE = 'duplicate',
  HIGH_APPLICANTS = 'high_applicants',
  LOCATION_UNFIT = 'location_unfit',
  POSTED_TOO_LONG_AGO = 'posted_too_long_ago'
}
