import { InjectionToken } from '@needle-di/core';
import type {
  AddBullet,
  AddBullet2,
  AddBulletVariant,
  AddSkillItem,
  ApproveBulletVariant,
  BulkChangeJobStatus,
  ChangeJobStatus,
  CreateArchetype,
  CreateCompany,
  CreateEducation,
  CreateEducation2,
  CreateExperience,
  CreateHeadline,
  CreateHeadline2,
  CreatePosition,
  CreateSkillCategory,
  DeleteArchetype,
  DeleteBullet,
  DeleteBullet2,
  DeleteBulletVariant,
  DeleteCompany,
  DeleteEducation,
  DeleteEducation2,
  DeleteExperience,
  DeleteHeadline,
  DeleteHeadline2,
  DeletePosition,
  DeleteSkillCategory,
  DeleteSkillItem,
  GenerateCompanyBrief,
  GenerateResume,
  GetCompanyBrief,
  GetJob,
  GetJobCompany,
  GetProfile,
  GetUser,
  IngestJobByUrl,
  IngestScrapedJob,
  JobScraper,
  ListArchetypes,
  ListCompanies,
  ListEducation,
  ListEducation2,
  ListExperiences,
  ListHeadlines,
  ListHeadlines2,
  ListJobs,
  ListSkillCategories,
  ListTags,
  LlmService,
  ReplaceLocations,
  ResumeContentFactory,
  ResumeRenderer,
  ScrapeAndIngestJobs,
  SetArchetypeEducation,
  SetArchetypePositions,
  SetArchetypeSkills,
  UpdateArchetype,
  UpdateBullet,
  UpdateBullet2,
  UpdateBulletVariant,
  UpdateCompany,
  UpdateEducation,
  UpdateEducation2,
  UpdateExperience,
  UpdateHeadline,
  UpdateHeadline2,
  UpdateJobCompany,
  UpdatePosition,
  UpdateProfile,
  UpdateSkillCategory,
  UpdateSkillItem,
  UpdateUser,
  WebColorService
} from '@tailoredin/application';
import type {
  ArchetypeConfigRepository,
  CompanyBriefRepository,
  CompanyRepository,
  EducationRepository,
  ExperienceRepository,
  HeadlineRepository,
  JobElector,
  JobRepository,
  ProfileRepository,
  ResumeCompanyRepository,
  ResumeEducationRepository,
  ResumeHeadlineRepository,
  ResumeSkillCategoryRepository,
  SkillCategoryRepository,
  SkillRepository,
  TagRepository,
  UserRepository
} from '@tailoredin/domain';

export const DI = {
  Job: {
    Repository: new InjectionToken<JobRepository>('DI.Job.Repository'),
    CompanyRepository: new InjectionToken<CompanyRepository>('DI.Job.CompanyRepository'),
    SkillRepository: new InjectionToken<SkillRepository>('DI.Job.SkillRepository'),
    Elector: new InjectionToken<JobElector>('DI.Job.Elector'),
    Scraper: new InjectionToken<JobScraper>('DI.Job.Scraper'),
    IngestJobByUrl: new InjectionToken<IngestJobByUrl>('DI.Job.IngestJobByUrl'),
    IngestScrapedJob: new InjectionToken<IngestScrapedJob>('DI.Job.IngestScrapedJob'),
    ScrapeAndIngestJobs: new InjectionToken<ScrapeAndIngestJobs>('DI.Job.ScrapeAndIngestJobs'),
    GetJob: new InjectionToken<GetJob>('DI.Job.GetJob'),
    ChangeJobStatus: new InjectionToken<ChangeJobStatus>('DI.Job.ChangeJobStatus'),
    BulkChangeJobStatus: new InjectionToken<BulkChangeJobStatus>('DI.Job.BulkChangeJobStatus'),
    ListJobs: new InjectionToken<ListJobs>('DI.Job.ListJobs'),
    GetJobCompany: new InjectionToken<GetJobCompany>('DI.Job.GetJobCompany'),
    UpdateJobCompany: new InjectionToken<UpdateJobCompany>('DI.Job.UpdateJobCompany')
  },

  Resume: {
    UserRepository: new InjectionToken<UserRepository>('DI.Resume.UserRepository'),
    CompanyRepository: new InjectionToken<ResumeCompanyRepository>('DI.Resume.CompanyRepository'),
    EducationRepository: new InjectionToken<ResumeEducationRepository>('DI.Resume.EducationRepository'),
    HeadlineRepository: new InjectionToken<ResumeHeadlineRepository>('DI.Resume.HeadlineRepository'),
    SkillCategoryRepository: new InjectionToken<ResumeSkillCategoryRepository>('DI.Resume.SkillCategoryRepository'),
    ArchetypeConfigRepository: new InjectionToken<ArchetypeConfigRepository>('DI.Resume.ArchetypeConfigRepository'),
    LlmService: new InjectionToken<LlmService | null>('DI.Resume.LlmService'),
    WebColorService: new InjectionToken<WebColorService>('DI.Resume.WebColorService'),
    Renderer: new InjectionToken<ResumeRenderer>('DI.Resume.Renderer'),
    ContentFactory: new InjectionToken<ResumeContentFactory>('DI.Resume.ContentFactory'),
    GenerateResume: new InjectionToken<GenerateResume>('DI.Resume.GenerateResume'),
    GetUser: new InjectionToken<GetUser>('DI.Resume.GetUser'),
    UpdateUser: new InjectionToken<UpdateUser>('DI.Resume.UpdateUser'),
    ListEducation: new InjectionToken<ListEducation>('DI.Resume.ListEducation'),
    CreateEducation: new InjectionToken<CreateEducation>('DI.Resume.CreateEducation'),
    UpdateEducation: new InjectionToken<UpdateEducation>('DI.Resume.UpdateEducation'),
    DeleteEducation: new InjectionToken<DeleteEducation>('DI.Resume.DeleteEducation'),
    ListHeadlines: new InjectionToken<ListHeadlines>('DI.Resume.ListHeadlines'),
    CreateHeadline: new InjectionToken<CreateHeadline>('DI.Resume.CreateHeadline'),
    UpdateHeadline: new InjectionToken<UpdateHeadline>('DI.Resume.UpdateHeadline'),
    DeleteHeadline: new InjectionToken<DeleteHeadline>('DI.Resume.DeleteHeadline'),
    ListCompanies: new InjectionToken<ListCompanies>('DI.Resume.ListCompanies'),
    CreateCompany: new InjectionToken<CreateCompany>('DI.Resume.CreateCompany'),
    UpdateCompany: new InjectionToken<UpdateCompany>('DI.Resume.UpdateCompany'),
    DeleteCompany: new InjectionToken<DeleteCompany>('DI.Resume.DeleteCompany'),
    CreatePosition: new InjectionToken<CreatePosition>('DI.Resume.CreatePosition'),
    UpdatePosition: new InjectionToken<UpdatePosition>('DI.Resume.UpdatePosition'),
    DeletePosition: new InjectionToken<DeletePosition>('DI.Resume.DeletePosition'),
    AddBullet: new InjectionToken<AddBullet>('DI.Resume.AddBullet'),
    UpdateBullet: new InjectionToken<UpdateBullet>('DI.Resume.UpdateBullet'),
    DeleteBullet: new InjectionToken<DeleteBullet>('DI.Resume.DeleteBullet'),
    ReplaceLocations: new InjectionToken<ReplaceLocations>('DI.Resume.ReplaceLocations')
  },

  Profile: {
    Repository: new InjectionToken<ProfileRepository>('DI.Profile.Repository'),
    GetProfile: new InjectionToken<GetProfile>('DI.Profile.GetProfile'),
    UpdateProfile: new InjectionToken<UpdateProfile>('DI.Profile.UpdateProfile')
  },

  CompanyBrief: {
    Repository: new InjectionToken<CompanyBriefRepository>('DI.CompanyBrief.Repository'),
    GenerateCompanyBrief: new InjectionToken<GenerateCompanyBrief>('DI.CompanyBrief.GenerateCompanyBrief'),
    GetCompanyBrief: new InjectionToken<GetCompanyBrief>('DI.CompanyBrief.GetCompanyBrief')
  },

  Headline: {
    Repository: new InjectionToken<HeadlineRepository>('DI.Headline.Repository'),
    List: new InjectionToken<ListHeadlines2>('DI.Headline.List'),
    Create: new InjectionToken<CreateHeadline2>('DI.Headline.Create'),
    Update: new InjectionToken<UpdateHeadline2>('DI.Headline.Update'),
    Delete: new InjectionToken<DeleteHeadline2>('DI.Headline.Delete')
  },

  Tag: {
    Repository: new InjectionToken<TagRepository>('DI.Tag.Repository'),
    List: new InjectionToken<ListTags>('DI.Tag.List')
  },

  Education: {
    Repository: new InjectionToken<EducationRepository>('DI.Education.Repository'),
    ListEducation: new InjectionToken<ListEducation2>('DI.Education.ListEducation'),
    CreateEducation: new InjectionToken<CreateEducation2>('DI.Education.CreateEducation'),
    UpdateEducation: new InjectionToken<UpdateEducation2>('DI.Education.UpdateEducation'),
    DeleteEducation: new InjectionToken<DeleteEducation2>('DI.Education.DeleteEducation')
  },

  SkillCategory: {
    Repository: new InjectionToken<SkillCategoryRepository>('DI.SkillCategory.Repository'),
    ListSkillCategories: new InjectionToken<ListSkillCategories>('DI.SkillCategory.ListSkillCategories'),
    CreateSkillCategory: new InjectionToken<CreateSkillCategory>('DI.SkillCategory.CreateSkillCategory'),
    UpdateSkillCategory: new InjectionToken<UpdateSkillCategory>('DI.SkillCategory.UpdateSkillCategory'),
    DeleteSkillCategory: new InjectionToken<DeleteSkillCategory>('DI.SkillCategory.DeleteSkillCategory'),
    AddSkillItem: new InjectionToken<AddSkillItem>('DI.SkillCategory.AddSkillItem'),
    UpdateSkillItem: new InjectionToken<UpdateSkillItem>('DI.SkillCategory.UpdateSkillItem'),
    DeleteSkillItem: new InjectionToken<DeleteSkillItem>('DI.SkillCategory.DeleteSkillItem')
  },

  Experience: {
    Repository: new InjectionToken<ExperienceRepository>('DI.Experience.Repository'),
    List: new InjectionToken<ListExperiences>('DI.Experience.List'),
    Create: new InjectionToken<CreateExperience>('DI.Experience.Create'),
    Update: new InjectionToken<UpdateExperience>('DI.Experience.Update'),
    Delete: new InjectionToken<DeleteExperience>('DI.Experience.Delete'),
    AddBullet: new InjectionToken<AddBullet2>('DI.Experience.AddBullet'),
    UpdateBullet: new InjectionToken<UpdateBullet2>('DI.Experience.UpdateBullet'),
    DeleteBullet: new InjectionToken<DeleteBullet2>('DI.Experience.DeleteBullet'),
    AddVariant: new InjectionToken<AddBulletVariant>('DI.Experience.AddVariant'),
    UpdateVariant: new InjectionToken<UpdateBulletVariant>('DI.Experience.UpdateVariant'),
    DeleteVariant: new InjectionToken<DeleteBulletVariant>('DI.Experience.DeleteVariant'),
    ApproveVariant: new InjectionToken<ApproveBulletVariant>('DI.Experience.ApproveVariant')
  },

  Archetype: {
    ConfigRepository: new InjectionToken<ArchetypeConfigRepository>('DI.Archetype.ConfigRepository'),
    ListArchetypes: new InjectionToken<ListArchetypes>('DI.Archetype.ListArchetypes'),
    CreateArchetype: new InjectionToken<CreateArchetype>('DI.Archetype.CreateArchetype'),
    UpdateArchetype: new InjectionToken<UpdateArchetype>('DI.Archetype.UpdateArchetype'),
    DeleteArchetype: new InjectionToken<DeleteArchetype>('DI.Archetype.DeleteArchetype'),
    SetPositions: new InjectionToken<SetArchetypePositions>('DI.Archetype.SetPositions'),
    SetSkills: new InjectionToken<SetArchetypeSkills>('DI.Archetype.SetSkills'),
    SetEducation: new InjectionToken<SetArchetypeEducation>('DI.Archetype.SetEducation')
  }
};
