import { InjectionToken } from '@needle-di/core';
import type {
  AddBullet,
  AddSkillItem,
  ChangeJobStatus,
  CreateArchetype,
  CreateCompany,
  CreateEducation,
  CreateHeadline,
  CreateSkillCategory,
  DeleteArchetype,
  DeleteBullet,
  DeleteCompany,
  DeleteEducation,
  DeleteHeadline,
  DeleteSkillCategory,
  DeleteSkillItem,
  GenerateResume,
  GetJob,
  GetJobCompany,
  GetTopJob,
  GetUser,
  IngestJobByUrl,
  IngestScrapedJob,
  JobScraper,
  ListArchetypes,
  ListCompanies,
  ListEducation,
  ListHeadlines,
  ListJobs,
  ListSkillCategories,
  LlmService,
  ReplaceLocations,
  ResumeContentFactory,
  ResumeRenderer,
  ScrapeAndIngestJobs,
  SetArchetypeEducation,
  SetArchetypePositions,
  SetArchetypeSkills,
  UpdateArchetype,
  UpdateBullet,
  UpdateCompany,
  UpdateEducation,
  UpdateHeadline,
  UpdateJobCompany,
  UpdateSkillCategory,
  UpdateSkillItem,
  UpdateUser,
  WebColorService
} from '@tailoredin/application';
import type {
  ArchetypeConfigRepository,
  CompanyRepository,
  JobElector,
  JobRepository,
  ResumeCompanyRepository,
  ResumeEducationRepository,
  ResumeHeadlineRepository,
  ResumeSkillCategoryRepository,
  SkillRepository,
  UserRepository
} from '@tailoredin/domain';

export const DI = {
  Job: {
    Repository: new InjectionToken<JobRepository>('DI.Job.Repository'),
    CompanyRepository: new InjectionToken<CompanyRepository>('DI.Job.CompanyRepository'),
    SkillRepository: new InjectionToken<SkillRepository>('DI.Job.SkillRepository'),
    Elector: new InjectionToken<JobElector>('DI.Job.Elector'),
    Scraper: new InjectionToken<JobScraper>('DI.Job.Scraper'),
    IngestJobByUrl: new InjectionToken<IngestJobByUrl>('DI.Job.IngestJobByUrl'),
    IngestScrapedJob: new InjectionToken<IngestScrapedJob>('DI.Job.IngestScrapedJob'),
    ScrapeAndIngestJobs: new InjectionToken<ScrapeAndIngestJobs>('DI.Job.ScrapeAndIngestJobs'),
    GetTopJob: new InjectionToken<GetTopJob>('DI.Job.GetTopJob'),
    GetJob: new InjectionToken<GetJob>('DI.Job.GetJob'),
    ChangeJobStatus: new InjectionToken<ChangeJobStatus>('DI.Job.ChangeJobStatus'),
    ListJobs: new InjectionToken<ListJobs>('DI.Job.ListJobs'),
    GetJobCompany: new InjectionToken<GetJobCompany>('DI.Job.GetJobCompany'),
    UpdateJobCompany: new InjectionToken<UpdateJobCompany>('DI.Job.UpdateJobCompany')
  },

  Resume: {
    UserRepository: new InjectionToken<UserRepository>('DI.Resume.UserRepository'),
    CompanyRepository: new InjectionToken<ResumeCompanyRepository>('DI.Resume.CompanyRepository'),
    EducationRepository: new InjectionToken<ResumeEducationRepository>('DI.Resume.EducationRepository'),
    HeadlineRepository: new InjectionToken<ResumeHeadlineRepository>('DI.Resume.HeadlineRepository'),
    SkillCategoryRepository: new InjectionToken<ResumeSkillCategoryRepository>('DI.Resume.SkillCategoryRepository'),
    ArchetypeConfigRepository: new InjectionToken<ArchetypeConfigRepository>('DI.Resume.ArchetypeConfigRepository'),
    LlmService: new InjectionToken<LlmService | null>('DI.Resume.LlmService'),
    WebColorService: new InjectionToken<WebColorService>('DI.Resume.WebColorService'),
    Renderer: new InjectionToken<ResumeRenderer>('DI.Resume.Renderer'),
    ContentFactory: new InjectionToken<ResumeContentFactory>('DI.Resume.ContentFactory'),
    GenerateResume: new InjectionToken<GenerateResume>('DI.Resume.GenerateResume'),
    GetUser: new InjectionToken<GetUser>('DI.Resume.GetUser'),
    UpdateUser: new InjectionToken<UpdateUser>('DI.Resume.UpdateUser'),
    ListEducation: new InjectionToken<ListEducation>('DI.Resume.ListEducation'),
    CreateEducation: new InjectionToken<CreateEducation>('DI.Resume.CreateEducation'),
    UpdateEducation: new InjectionToken<UpdateEducation>('DI.Resume.UpdateEducation'),
    DeleteEducation: new InjectionToken<DeleteEducation>('DI.Resume.DeleteEducation'),
    ListHeadlines: new InjectionToken<ListHeadlines>('DI.Resume.ListHeadlines'),
    CreateHeadline: new InjectionToken<CreateHeadline>('DI.Resume.CreateHeadline'),
    UpdateHeadline: new InjectionToken<UpdateHeadline>('DI.Resume.UpdateHeadline'),
    DeleteHeadline: new InjectionToken<DeleteHeadline>('DI.Resume.DeleteHeadline'),
    ListCompanies: new InjectionToken<ListCompanies>('DI.Resume.ListCompanies'),
    CreateCompany: new InjectionToken<CreateCompany>('DI.Resume.CreateCompany'),
    UpdateCompany: new InjectionToken<UpdateCompany>('DI.Resume.UpdateCompany'),
    DeleteCompany: new InjectionToken<DeleteCompany>('DI.Resume.DeleteCompany'),
    AddBullet: new InjectionToken<AddBullet>('DI.Resume.AddBullet'),
    UpdateBullet: new InjectionToken<UpdateBullet>('DI.Resume.UpdateBullet'),
    DeleteBullet: new InjectionToken<DeleteBullet>('DI.Resume.DeleteBullet'),
    ReplaceLocations: new InjectionToken<ReplaceLocations>('DI.Resume.ReplaceLocations'),
    ListSkillCategories: new InjectionToken<ListSkillCategories>('DI.Resume.ListSkillCategories'),
    CreateSkillCategory: new InjectionToken<CreateSkillCategory>('DI.Resume.CreateSkillCategory'),
    UpdateSkillCategory: new InjectionToken<UpdateSkillCategory>('DI.Resume.UpdateSkillCategory'),
    DeleteSkillCategory: new InjectionToken<DeleteSkillCategory>('DI.Resume.DeleteSkillCategory'),
    AddSkillItem: new InjectionToken<AddSkillItem>('DI.Resume.AddSkillItem'),
    UpdateSkillItem: new InjectionToken<UpdateSkillItem>('DI.Resume.UpdateSkillItem'),
    DeleteSkillItem: new InjectionToken<DeleteSkillItem>('DI.Resume.DeleteSkillItem')
  },

  Archetype: {
    ConfigRepository: new InjectionToken<ArchetypeConfigRepository>('DI.Archetype.ConfigRepository'),
    ListArchetypes: new InjectionToken<ListArchetypes>('DI.Archetype.ListArchetypes'),
    CreateArchetype: new InjectionToken<CreateArchetype>('DI.Archetype.CreateArchetype'),
    UpdateArchetype: new InjectionToken<UpdateArchetype>('DI.Archetype.UpdateArchetype'),
    DeleteArchetype: new InjectionToken<DeleteArchetype>('DI.Archetype.DeleteArchetype'),
    SetPositions: new InjectionToken<SetArchetypePositions>('DI.Archetype.SetPositions'),
    SetSkills: new InjectionToken<SetArchetypeSkills>('DI.Archetype.SetSkills'),
    SetEducation: new InjectionToken<SetArchetypeEducation>('DI.Archetype.SetEducation')
  }
};
