/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ResumeSkillsRouteImport } from './routes/resume/skills'
import { Route as ResumeBuilderRouteImport } from './routes/resume/builder'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies/$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeSkillsRoute = ResumeSkillsRouteImport.update({
  id: '/resume/skills',
  path: '/resume/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume/builder',
  path: '/resume/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resume/builder': typeof ResumeBuilderRoute
  '/resume/skills': typeof ResumeSkillsRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resume/builder': typeof ResumeBuilderRoute
  '/resume/skills': typeof ResumeSkillsRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resume/builder': typeof ResumeBuilderRoute
  '/resume/skills': typeof ResumeSkillsRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies/$companyId'
    | '/jobs/$jobId'
    | '/resume/builder'
    | '/resume/skills'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies/$companyId'
    | '/jobs/$jobId'
    | '/resume/builder'
    | '/resume/skills'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/companies/$companyId'
    | '/jobs/$jobId'
    | '/resume/builder'
    | '/resume/skills'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  ResumeSkillsRoute: typeof ResumeSkillsRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/skills': {
      id: '/resume/skills'
      path: '/resume/skills'
      fullPath: '/resume/skills'
      preLoaderRoute: typeof ResumeSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/builder': {
      id: '/resume/builder'
      path: '/resume/builder'
      fullPath: '/resume/builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  ResumeSkillsRoute: ResumeSkillsRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
