/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences/index'
import { Route as EducationIndexRouteImport } from './routes/education/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as JobDescriptionsJobDescriptionIdRouteImport } from './routes/job-descriptions/$jobDescriptionId'
import { Route as ExperiencesExperienceIdRouteImport } from './routes/experiences/$experienceId'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies/$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationIndexRoute = EducationIndexRouteImport.update({
  id: '/education/',
  path: '/education/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobDescriptionsJobDescriptionIdRoute =
  JobDescriptionsJobDescriptionIdRouteImport.update({
    id: '/job-descriptions/$jobDescriptionId',
    path: '/job-descriptions/$jobDescriptionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperiencesExperienceIdRoute = ExperiencesExperienceIdRouteImport.update({
  id: '/experiences/$experienceId',
  path: '/experiences/$experienceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
  '/job-descriptions/$jobDescriptionId': typeof JobDescriptionsJobDescriptionIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/education/': typeof EducationIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
  '/job-descriptions/$jobDescriptionId': typeof JobDescriptionsJobDescriptionIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/education': typeof EducationIndexRoute
  '/experiences': typeof ExperiencesIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
  '/job-descriptions/$jobDescriptionId': typeof JobDescriptionsJobDescriptionIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/education/': typeof EducationIndexRoute
  '/experiences/': typeof ExperiencesIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies/$companyId'
    | '/experiences/$experienceId'
    | '/job-descriptions/$jobDescriptionId'
    | '/companies/'
    | '/education/'
    | '/experiences/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies/$companyId'
    | '/experiences/$experienceId'
    | '/job-descriptions/$jobDescriptionId'
    | '/companies'
    | '/education'
    | '/experiences'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/companies/$companyId'
    | '/experiences/$experienceId'
    | '/job-descriptions/$jobDescriptionId'
    | '/companies/'
    | '/education/'
    | '/experiences/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  ExperiencesExperienceIdRoute: typeof ExperiencesExperienceIdRoute
  JobDescriptionsJobDescriptionIdRoute: typeof JobDescriptionsJobDescriptionIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  EducationIndexRoute: typeof EducationIndexRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/': {
      id: '/education/'
      path: '/education'
      fullPath: '/education/'
      preLoaderRoute: typeof EducationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-descriptions/$jobDescriptionId': {
      id: '/job-descriptions/$jobDescriptionId'
      path: '/job-descriptions/$jobDescriptionId'
      fullPath: '/job-descriptions/$jobDescriptionId'
      preLoaderRoute: typeof JobDescriptionsJobDescriptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$experienceId': {
      id: '/experiences/$experienceId'
      path: '/experiences/$experienceId'
      fullPath: '/experiences/$experienceId'
      preLoaderRoute: typeof ExperiencesExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  ExperiencesExperienceIdRoute: ExperiencesExperienceIdRoute,
  JobDescriptionsJobDescriptionIdRoute: JobDescriptionsJobDescriptionIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  EducationIndexRoute: EducationIndexRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
