/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ArchetypesIndexRouteImport } from './routes/archetypes/index'
import { Route as ResumeSkillsRouteImport } from './routes/resume/skills'
import { Route as ResumeProfileRouteImport } from './routes/resume/profile'
import { Route as ResumeExperienceRouteImport } from './routes/resume/experience'
import { Route as ResumeEducationRouteImport } from './routes/resume/education'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as ArchetypesArchetypeIdRouteImport } from './routes/archetypes/$archetypeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypesIndexRoute = ArchetypesIndexRouteImport.update({
  id: '/archetypes/',
  path: '/archetypes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeSkillsRoute = ResumeSkillsRouteImport.update({
  id: '/resume/skills',
  path: '/resume/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeProfileRoute = ResumeProfileRouteImport.update({
  id: '/resume/profile',
  path: '/resume/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeExperienceRoute = ResumeExperienceRouteImport.update({
  id: '/resume/experience',
  path: '/resume/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeEducationRoute = ResumeEducationRouteImport.update({
  id: '/resume/education',
  path: '/resume/education',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchetypesArchetypeIdRoute = ArchetypesArchetypeIdRouteImport.update({
  id: '/archetypes/$archetypeId',
  path: '/archetypes/$archetypeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archetypes/$archetypeId': typeof ArchetypesArchetypeIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resume/education': typeof ResumeEducationRoute
  '/resume/experience': typeof ResumeExperienceRoute
  '/resume/profile': typeof ResumeProfileRoute
  '/resume/skills': typeof ResumeSkillsRoute
  '/archetypes/': typeof ArchetypesIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archetypes/$archetypeId': typeof ArchetypesArchetypeIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resume/education': typeof ResumeEducationRoute
  '/resume/experience': typeof ResumeExperienceRoute
  '/resume/profile': typeof ResumeProfileRoute
  '/resume/skills': typeof ResumeSkillsRoute
  '/archetypes': typeof ArchetypesIndexRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archetypes/$archetypeId': typeof ArchetypesArchetypeIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resume/education': typeof ResumeEducationRoute
  '/resume/experience': typeof ResumeExperienceRoute
  '/resume/profile': typeof ResumeProfileRoute
  '/resume/skills': typeof ResumeSkillsRoute
  '/archetypes/': typeof ArchetypesIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archetypes/$archetypeId'
    | '/jobs/$jobId'
    | '/resume/education'
    | '/resume/experience'
    | '/resume/profile'
    | '/resume/skills'
    | '/archetypes/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archetypes/$archetypeId'
    | '/jobs/$jobId'
    | '/resume/education'
    | '/resume/experience'
    | '/resume/profile'
    | '/resume/skills'
    | '/archetypes'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/archetypes/$archetypeId'
    | '/jobs/$jobId'
    | '/resume/education'
    | '/resume/experience'
    | '/resume/profile'
    | '/resume/skills'
    | '/archetypes/'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchetypesArchetypeIdRoute: typeof ArchetypesArchetypeIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ResumeEducationRoute: typeof ResumeEducationRoute
  ResumeExperienceRoute: typeof ResumeExperienceRoute
  ResumeProfileRoute: typeof ResumeProfileRoute
  ResumeSkillsRoute: typeof ResumeSkillsRoute
  ArchetypesIndexRoute: typeof ArchetypesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetypes/': {
      id: '/archetypes/'
      path: '/archetypes'
      fullPath: '/archetypes/'
      preLoaderRoute: typeof ArchetypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/skills': {
      id: '/resume/skills'
      path: '/resume/skills'
      fullPath: '/resume/skills'
      preLoaderRoute: typeof ResumeSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/profile': {
      id: '/resume/profile'
      path: '/resume/profile'
      fullPath: '/resume/profile'
      preLoaderRoute: typeof ResumeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/experience': {
      id: '/resume/experience'
      path: '/resume/experience'
      fullPath: '/resume/experience'
      preLoaderRoute: typeof ResumeExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/education': {
      id: '/resume/education'
      path: '/resume/education'
      fullPath: '/resume/education'
      preLoaderRoute: typeof ResumeEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archetypes/$archetypeId': {
      id: '/archetypes/$archetypeId'
      path: '/archetypes/$archetypeId'
      fullPath: '/archetypes/$archetypeId'
      preLoaderRoute: typeof ArchetypesArchetypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchetypesArchetypeIdRoute: ArchetypesArchetypeIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ResumeEducationRoute: ResumeEducationRoute,
  ResumeExperienceRoute: ResumeExperienceRoute,
  ResumeProfileRoute: ResumeProfileRoute,
  ResumeSkillsRoute: ResumeSkillsRoute,
  ArchetypesIndexRoute: ArchetypesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
